### ISSUE TITLE
Allow playtime containing ~ prefix

### ISSUE THREAD

**Issue by deefha** [deefha/nyx-dohrano#14]
e.g.:

```
- content: 'Still Wakes the Deep / ~7h / PC Xbox Gamepass / #dohrano'
  source_data:
  - original: Still Wakes the Deep
    type: game
    value: Still Wakes the Deep
  - original: ~7h
    type: platform
    value: ~7h
  - original: PC Xbox Gamepass
    type: platform
    value: PC Xbox Gamepass
  source_line: 'Still Wakes the Deep / ~7h / PC Xbox Gamepass / #dohrano'
  source_parts:
  - Still Wakes the Deep
  - ~7h
  - PC Xbox Gamepass
  status: PLAYTIME_MISSING
```
